swagger: '2.0'
info:
  title: Intelligent Search API
  description: 'API to recieve intelligent search results based on query.'
  version: 1.0.0
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /intelligent-search:
    get:
      summary: Search results consolidated across discussion-based apps
      description: Returns an intelligent summary of relevant opinions, groups them by key claims and provides top comments supporting each claim. 
      parameters:
        - name: search_query
          in: query
          description: Search query
          type: string
          required: true
        - name: user_id
          in: header
          description: User ID to store state
          type: string
          required: true
        - name: search_id
          in: header
          description: Unique search ID
          type: string
          required: true
      responses:
        200:
          description: Intelligent search results
          schema:
            type: object
            properties:
              search_id:
                type: string
              summary:
                type: string
              key_claims:
                type: array
                items:
                  type: object
                  properties:
                    claim:
                      type: string
                    relevance_score:
                      type: integer
                      format: int32
                    supporting_comments:
                      type: array
                      items:
                        type: string
        400:
          description: Not Authorized
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string