swagger: '2.0'
info:
  title: User Login API
  description: 'API to authenticate user access through login'
  version: 1.0.0
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /user-login:
    get:
      summary: Logs user into the system
      description: Authenticates user access by checking username and password validity.
      parameters:
        - name: username
          in: query
          description: The username for login
          type: string
          required: true
        - name: password
          in: query
          description: The password for login
          type: string
          required: true
      responses:
        200:
          description: Successful login
          headers:
            X-Expires-After:
              description: date in UTC when token expires
              type: string
              format: date-time
        400:
          description: Invalid username/password